/* Output from p2c 2.00.Oct.15, the Pascal-to-C translator */
/* From input file "surprisal.p" */


 #include "/root/src/p2c-2.01/home/src/p2c.h"


/*







*/



#define version         1.00
/*
*/
#define updateversion   1.00



/*












































*/


Static _TEXT histog, surprisalp, xyin;


Static jmp_buf _JL1;


Static Void halt()
{
  /*





*/
  printf(" program halt.\n");
  longjmp(_JL1, 1);
}



Static Void copyaline(fin, fout)
_TEXT *fin, *fout;
{
  while (!P_eoln(fin->f)) {
    putc(P_peek(fin->f), fout->f);
    getc(fin->f);
  }
  fscanf(fin->f, "%*[^\n]");
  getc(fin->f);
  putc('\n', fout->f);
}


#define wid             10
#define dec             8



Static Void themain(histog, xyin)
_TEXT *histog, *xyin;
{
  long numerator;
  double ln2 = log(2.0);
  double parameterversion;
  long position;
  long total = 0;

  printf("surprisal %4.2f\n", version);

  if (*surprisalp.name != '\0') {
    if (surprisalp.f != NULL)
      surprisalp.f = freopen(surprisalp.name, "r", surprisalp.f);
    else
      surprisalp.f = fopen(surprisalp.name, "r");
  } else
    rewind(surprisalp.f);
  if (surprisalp.f == NULL)
    _EscIO2(FileNotFound, surprisalp.name);
  RESETBUF(surprisalp.f, Char);
  fscanf(surprisalp.f, "%lg%*[^\n]", &parameterversion);
  getc(surprisalp.f);
  if (parameterversion < updateversion) {
    printf("You have an old parameter file!\n");
    halt();
  }

  if (*xyin->name != '\0') {
    if (xyin->f != NULL)
      xyin->f = freopen(xyin->name, "w", xyin->f);
    else
      xyin->f = fopen(xyin->name, "w");
  } else {
    if (xyin->f != NULL)
      rewind(xyin->f);
    else
      xyin->f = tmpfile();
  }
  if (xyin->f == NULL)
    _EscIO2(FileNotFound, xyin->name);
  SETUPBUF(xyin->f, Char);
  fprintf(xyin->f, "* surprisal %4.2f\n", version);
  if (*histog->name != '\0') {
    if (histog->f != NULL)
      histog->f = freopen(histog->name, "r", histog->f);
    else
      histog->f = fopen(histog->name, "r");
  } else
    rewind(histog->f);
  if (histog->f == NULL)
    _EscIO2(FileNotFound, histog->name);
  RESETBUF(histog->f, Char);

  while (!BUFEOF(histog->f)) {
    if (P_eoln(histog->f)) {
      fscanf(histog->f, "%*[^\n]");
      getc(histog->f);
      continue;
    }
    if (P_peek(histog->f) == '*') {
      fscanf(histog->f, "%*[^\n]");
      getc(histog->f);
    } else {
      fscanf(histog->f, "%ld%ld%*[^\n]", &position, &numerator);
      getc(histog->f);
      total += numerator;
    }
  }

  if (*histog->name != '\0') {
    if (histog->f != NULL)
      histog->f = freopen(histog->name, "r", histog->f);
    else
      histog->f = fopen(histog->name, "r");
  } else
    rewind(histog->f);
  if (histog->f == NULL)
    _EscIO2(FileNotFound, histog->name);
  RESETBUF(histog->f, Char);

  fprintf(xyin->f, "*\n");
  fprintf(xyin->f, "* columns generated by the surprisal program:\n");
  fprintf(xyin->f, "* 1: position\n");
  fprintf(xyin->f, "* 2: -log2(frequency), surprisal in bits\n");
  fprintf(xyin->f, "* 3: frequency\n");
  fprintf(xyin->f, "* 4: original count in this bin\n\n");

  while (!BUFEOF(histog->f)) {
    if (P_eoln(histog->f)) {
      fscanf(histog->f, "%*[^\n]");
      getc(histog->f);
      continue;
    }
    if (P_peek(histog->f) == '*')
      copyaline(histog, xyin);
    else {
      fscanf(histog->f, "%ld%ld%*[^\n]", &position, &numerator);
      getc(histog->f);
      fprintf(xyin->f, "%ld %*.*f %*.*f %ld\n",
	      position, wid, dec, -(log((double)numerator / total) / ln2),
	      wid, dec, (double)numerator / total, numerator);
    }
  }

}

#undef wid
#undef dec


main(argc, argv)
int argc;
Char *argv[];
{
  PASCAL_MAIN(argc, argv);
  if (setjmp(_JL1))
    goto _L1;
  xyin.f = NULL;
  strcpy(xyin.name, "xyin");
  surprisalp.f = NULL;
  strcpy(surprisalp.name, "surprisalp");
  histog.f = NULL;
  strcpy(histog.name, "histog");
  themain(&histog, &xyin);
_L1:
  if (histog.f != NULL)
    fclose(histog.f);
  if (surprisalp.f != NULL)
    fclose(surprisalp.f);
  if (xyin.f != NULL)
    fclose(xyin.f);
  exit(EXIT_SUCCESS);
}



/* End. */
